syntax = "proto3";

option java_multiple_files = true;
option java_package = "generated";

package slaughterhouse;
service SlaughterHouse
{
  rpc GetAnimalsByProduct(ProductRequest) returns (AnimalListResponse);
  rpc GetProductsByAnimal(AnimalRequest) returns (ProductListResponse);
}

message ProductRequest {
  int32 product_id = 1;
}

message AnimalRequest {
  int32 animal_id = 1;
}

message Animal
{
  int32 animal_id = 1;
  string registration_number = 2;
  double weight = 3;
  string type = 4;
}

message AnimalPart
{
  int32 part_id = 1;
  double weight = 2;
  string type_part = 3;
  int32 animal_id = 4;
}

message Tray
{
  int32 tray_id = 1;
  double max_weight = 2;
  repeated AnimalPart animal_parts = 3;
}

message Product
{
  int32 product_id = 1;
  string product_type = 2;
  repeated int32 tray_ids = 3;
}

message AnimalListResponse {
  repeated Animal animals = 1;
}

message ProductListResponse {
  repeated Product products = 1;
}